from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field


@dataclass(frozen=True)
class FlowCase:
    case_id: str
    title: str
    kind: str
    summary: str
    expected_pr_check: str
    expected_merge_check: str
    expected_ingest: str
    must_finalize: bool
    expected_post_ingest_merge: str = "skip"
    accepted_examples: int = 0
    needs_rejected_rows: int = 0
    mutations: tuple[str, ...] = ()
    notes: tuple[str, ...] = field(default_factory=tuple)
    expected_codes: tuple[str, ...] = ()


HIGH_VALUE_CASE_IDS: tuple[str, ...] = (
    "T01",
    "T02",
    "T03",
    "T04",
    "T05",
    "T06",
    "T08",
    "T10",
    "T16",
    "T18",
)


CASES: tuple[FlowCase, ...] = (
    FlowCase(
        case_id="T01",
        title="empty-data-empty-staging",
        kind="data-baseline",
        summary="`data` 为空，`staging` 为空。",
        expected_pr_check="pass",
        expected_merge_check="pass",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
    ),
    FlowCase(
        case_id="T02",
        title="nonempty-data-empty-staging",
        kind="data-baseline",
        summary="`data` 非空，`staging` 为空。",
        expected_pr_check="pass",
        expected_merge_check="pass",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=1,
    ),
    FlowCase(
        case_id="T03",
        title="empty-data-valid-staging-accepted",
        kind="staging-happy-path",
        summary="`data` 为空，`staging/accepted` 有合法样例。",
        expected_pr_check="pass",
        expected_merge_check="fail",
        expected_ingest="pass",
        expected_post_ingest_merge="pass",
        must_finalize=True,
        accepted_examples=1,
    ),
    FlowCase(
        case_id="T04",
        title="empty-data-valid-staging-rejected",
        kind="staging-happy-path",
        summary="`data` 为空，`staging/rejected/rows.csv` 有合法样例。",
        expected_pr_check="pass",
        expected_merge_check="fail",
        expected_ingest="pass",
        expected_post_ingest_merge="pass",
        must_finalize=True,
        needs_rejected_rows=1,
    ),
    FlowCase(
        case_id="T05",
        title="nonempty-data-valid-staging-both",
        kind="staging-happy-path",
        summary="`data` 非空，`staging` 同时包含 accepted 与 rejected 合法样例。",
        expected_pr_check="pass",
        expected_merge_check="fail",
        expected_ingest="pass",
        expected_post_ingest_merge="pass",
        must_finalize=True,
        accepted_examples=2,
        needs_rejected_rows=1,
    ),
    FlowCase(
        case_id="T06",
        title="staging-accepted-conflicts-with-data-accepted",
        kind="staging-conflict",
        summary="staging accepted 与正式 accepted 冲突。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=1,
        mutations=("duplicate_into_data_accepted",),
        expected_codes=("staging_accepted_conflict_accepted",),
    ),
    FlowCase(
        case_id="T07",
        title="staging-accepted-conflicts-with-data-rejected",
        kind="staging-conflict",
        summary="staging accepted 与正式 rejected 冲突。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=1,
        needs_rejected_rows=1,
        mutations=("match_data_rejected_url_to_staging_accepted",),
        expected_codes=("staging_accepted_conflict_rejected",),
    ),
    FlowCase(
        case_id="T08",
        title="staging-rejected-conflicts-with-data-rejected",
        kind="staging-conflict",
        summary="staging rejected 与正式 rejected 冲突。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        needs_rejected_rows=1,
        mutations=("duplicate_into_data_rejected",),
        expected_codes=("staging_rejected_conflict_rejected",),
    ),
    FlowCase(
        case_id="T09",
        title="staging-rejected-conflicts-with-data-accepted",
        kind="staging-conflict",
        summary="staging rejected 与正式 accepted 冲突。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=1,
        needs_rejected_rows=1,
        mutations=("match_staging_rejected_url_to_data_accepted",),
        expected_codes=("staging_rejected_conflict_accepted",),
    ),
    FlowCase(
        case_id="T10",
        title="staging-accepted-duplicate-canonical-url",
        kind="staging-invalid",
        summary="staging accepted 内部重复。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=2,
        mutations=("duplicate_canonical_url_in_staging",),
        expected_codes=("staging_accepted_duplicate_canonical_url",),
    ),
    FlowCase(
        case_id="T11",
        title="staging-rejected-duplicate-url",
        kind="staging-invalid",
        summary="staging rejected 内部重复。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        needs_rejected_rows=2,
        mutations=("duplicate_url_in_staging_rejected",),
        expected_codes=("staging_rejected_duplicate_url",),
    ),
    FlowCase(
        case_id="T12",
        title="staging-unexpected-file",
        kind="staging-invalid",
        summary="staging 中存在不支持的文件。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        mutations=("create_unexpected_staging_file",),
        expected_codes=("staging_unexpected_file",),
    ),
    FlowCase(
        case_id="T13",
        title="staging-accepted-invalid-filename",
        kind="staging-invalid",
        summary="staging accepted 文件名非法，包括中文文件名。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=1,
        mutations=("invalid_staging_accepted_filename",),
        expected_codes=("staging_accepted_invalid_filename",),
    ),
    FlowCase(
        case_id="T14",
        title="staging-accepted-invalid-content",
        kind="staging-invalid",
        summary="staging accepted 内容结构非法。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=1,
        mutations=("invalid_staging_accepted_content",),
        expected_codes=("staging_accepted_invalid_canonical_url",),
    ),
    FlowCase(
        case_id="T15",
        title="staging-rejected-invalid-content",
        kind="staging-invalid",
        summary="staging rejected 表头或行结构非法。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        needs_rejected_rows=1,
        mutations=("invalid_staging_rejected_header",),
        expected_codes=("staging_rejected_invalid_header",),
    ),
    FlowCase(
        case_id="T16",
        title="invalid-data-accepted",
        kind="data-invalid",
        summary="正式 accepted 文件非法。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=1,
        mutations=("remove_required_summary_field",),
        expected_codes=("accepted_missing_field",),
    ),
    FlowCase(
        case_id="T17",
        title="invalid-data-rejected",
        kind="data-invalid",
        summary="正式 rejected.csv 非法。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        needs_rejected_rows=1,
        mutations=("invalid_data_rejected_duplicate",),
        expected_codes=("rejected_duplicate_url",),
    ),
    FlowCase(
        case_id="T18",
        title="cross-conflict-between-data-accepted-and-rejected",
        kind="data-invalid",
        summary="同一规范化 URL 同时存在于正式 accepted 与正式 rejected。",
        expected_pr_check="fail",
        expected_merge_check="fail",
        expected_ingest="skip",
        expected_post_ingest_merge="skip",
        must_finalize=False,
        accepted_examples=1,
        needs_rejected_rows=1,
        mutations=("match_rejected_url_to_accepted_url",),
        expected_codes=("cross_url_conflict",),
    ),
    FlowCase(
        case_id="T19",
        title="pending-staging-boundary",
        kind="boundary",
        summary="push 后 pr-check 通过，但 merge-check 因 pending staging 失败。",
        expected_pr_check="pass",
        expected_merge_check="fail",
        expected_ingest="pass",
        expected_post_ingest_merge="pass",
        must_finalize=True,
        accepted_examples=1,
        expected_codes=("merge_pending_staging",),
    ),
    FlowCase(
        case_id="T20",
        title="post-ingest-merge-check-passes",
        kind="boundary",
        summary="ingest 成功后再次 merge-check 通过。",
        expected_pr_check="pass",
        expected_merge_check="fail",
        expected_ingest="pass",
        expected_post_ingest_merge="pass",
        must_finalize=True,
        accepted_examples=1,
        needs_rejected_rows=1,
    ),
)


def list_cases(*, high_value_only: bool = False) -> list[FlowCase]:
    if not high_value_only:
        return list(CASES)
    return [case for case in CASES if case.case_id in HIGH_VALUE_CASE_IDS]
